import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import sharp from 'sharp';

const ROOT=path.resolve(process.cwd());
const DATA=path.join(ROOT,'data');
const PHOTOS=path.join(ROOT,'assets','autores');
const MARKET_URL=process.env.MARKET_URL||'https://raw.githubusercontent.com/feliperibeirobittencourt/monitor-leiloes/refs/heads/main/leiloes.csv';
const COLLECTION_URL=process.env.COLLECTION_URL||'https://docs.google.com/spreadsheets/d/e/2PACX-1vS-LDhRitxzppadqsBHKYYSPy7hi6dJIYyUzX6reIP5ZAor2knWh4tR05Qq-X5EUPGVWYBLDtQTl_AG/pub?gid=416493939&single=true&output=csv';
const ESTANTE_CURRENT_URL=process.env.ESTANTE_CURRENT_URL||'';
const ESTANTE_HISTORY_URL=process.env.ESTANTE_HISTORY_URL||'';
const ESTANTE_CURRENT_FILE=process.env.ESTANTE_CURRENT_FILE||'raw/estante-hoje.csv';
const ESTANTE_HISTORY_FILE=process.env.ESTANTE_HISTORY_FILE||'raw/estante-historico.csv';
const PATRONS=["Adelino Fontoura","Álvares de Azevedo","Artur de Oliveira","Basílio da Gama","Bernardo Guimarães","Casimiro de Abreu","Castro Alves","Cláudio Manuel da Costa","Gonçalves de Magalhães","Evaristo da Veiga","Fagundes Varela","França Júnior","Francisco Otaviano","Franklin Távora","Gonçalves Dias","Gregório de Matos","Hipólito da Costa","João Francisco Lisboa","Joaquim Caetano da Silva","Joaquim Manuel de Macedo","Joaquim Serra","José Bonifácio","José de Alencar","Júlio Ribeiro","Junqueira Freire","Laurindo Rabelo","Maciel Monteiro","Manuel Antônio de Almeida","Martins Pena","Pardal Mallet","Pedro Luís","Araújo Porto-Alegre","Raul Pompeia","Sousa Caldas","Tavares Bastos","Teófilo Dias","Tomás Antônio Gonzaga","Tobias Barreto","Francisco Adolfo de Varnhagen","Visconde do Rio Branco"];
const FOUNDERS=["Luís Murat","Coelho Neto","Filinto de Almeida","Aluísio Azevedo","Raimundo Correia","Teixeira de Melo","Valentim Magalhães","Alberto de Oliveira","Carlos Magalhães de Azeredo","Rui Barbosa","Lúcio de Mendonça","Urbano Duarte","Visconde de Taunay","Clóvis Beviláqua","Olavo Bilac","Araripe Júnior","Sílvio Romero","José Veríssimo","Alcindo Guanabara","Salvador de Mendonça","José do Patrocínio","Medeiros e Albuquerque","Machado de Assis","Garcia Redondo","Franklin Dória","Guimarães Passos","Joaquim Nabuco","Inglês de Sousa","Artur Azevedo","Pedro Rabelo","Luís Guimarães Júnior","Carlos de Laet","Domício da Gama","J. M. Pereira da Silva","Rodrigo Octavio","Afonso Celso","Silva Ramos","Graça Aranha","Oliveira Lima","Eduardo Prado","Julia Lopes de Almeida"];
const PHOTO_OVERRIDES={"salvador de mendonca":"https://www.academia.org.br/sites/default/files/academicos/fotografias/salvador_de_mendonca_-_sme_f_001_-_copia.jpg","raul pompeia":"https://www.academia.org.br/sites/default/files/academicos/fotografias/raul-pompeia_0.jpg","jose bonifacio":"https://www.academia.org.br/sites/default/files/academicos/fotografias/jose-bonifacio.jpg","joao francisco lisboa":"https://www.academia.org.br/sites/default/files/academicos/fotografias/joao-francisco-lisboa-cad18.jpg","j m pereira da silva":"https://www.academia.org.br/sites/default/files/academicos/fotografias/pereira-da-silva-jm.jpg","ingles de sousa":"https://www.academia.org.br/sites/default/files/academicos/fotografias/ingles-de-souza.jpg","hipolito da costa":"https://www.academia.org.br/sites/default/files/academicos/fotografias/hipolito-jose-da-costa.jpg","franklin doria":"https://www.academia.org.br/sites/default/files/academicos/fotografias/barao-de-loreto-franklin-doria.jpg","francisco adolfo de varnhagen":"https://www.academia.org.br/sites/default/files/academicos/fotografias/francisco_adolfo_de_varnhagen.jpg","claudio manuel da costa":"https://www.academia.org.br/sites/default/files/academicos/fotografias/claudio-manuel-da-costa.jpg","carlos magalhaes de azeredo":"https://www.academia.org.br/sites/default/files/academicos/fotografias/magalhaes-de-azeredo.jpg","basilio da gama":"https://www.academia.org.br/sites/default/files/academicos/fotografias/basilio-da-gama-cad4.jpg","julia lopes de almeida":"https://www.bazardotempo.com.br/cdn/shop/files/Julia_Lopes_de_Almeida.jpg"};
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^\p{L}\p{N}]+/gu,' ').trim();
const slug=v=>norm(v).replace(/\s+/g,'-');
const extractYear=v=>{const m=String(v??'').match(/\b(1[5-9]\d{2}|20\d{2})\b/g);return m?Number(m.at(-1)):null};
const col=(row,names)=>{const entries=Object.entries(row);for(const n of names){const nn=norm(n);const hit=entries.find(([k])=>norm(k)===nn||norm(k).includes(nn));if(hit&&String(hit[1]??'').trim()!=='')return String(hit[1]).trim()}return''};
function parseDelimitedRows(text,delim){text=String(text||'').replace(/^\uFEFF/,'');const rows=[];let row=[],field='',quote=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quote&&n==='"'){field+='"';i++}else if(c==='"')quote=!quote;else if(c===delim&&!quote){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!quote){if(c==='\r'&&n==='\n')i++;row.push(field);field='';if(row.some(x=>String(x).trim()!==''))rows.push(row);row=[]}else field+=c}row.push(field);if(row.some(x=>String(x).trim()!==''))rows.push(row);return rows}
function rowsToObjects(rows,headerIndex){const headers=rows[headerIndex].map((x,i)=>String(x).trim()||`col_${i}`);return rows.slice(headerIndex+1).filter(r=>r.some(x=>String(x).trim()!=='')).map(r=>Object.fromEntries(headers.map((h,i)=>[h,(r[i]??'').trim()]))) }
function parseCSV(text){const lines=String(text||'').split(/\r?\n/).filter(Boolean).slice(0,8),ds=[';',',','\t'],score=d=>lines.reduce((s,l)=>s+(l.split(d).length-1),0),delim=[...ds].sort((a,b)=>score(b)-score(a))[0],rows=parseDelimitedRows(text,delim);return rows.length>1?rowsToObjects(rows,0):[]}
function parseCollectionCSV(text){for(const d of [',',';','\t']){const rows=parseDelimitedRows(text,d);for(let i=0;i<Math.min(50,rows.length);i++){const cells=rows[i].map(norm);if((cells.includes('autores')||cells.includes('autor'))&&cells.includes('titulo')&&cells.includes('tenho')){const headers=rows[i].map((x,j)=>String(x).trim()||`col_${j}`),out=[];for(let rowIndex=i+1;rowIndex<rows.length;rowIndex++){const row=rows[rowIndex];if(!row.some(x=>String(x).trim()!==''))continue;const obj=Object.fromEntries(headers.map((h,j)=>[h,(row[j]??'').trim()]));out.push({...obj,_sheetRow:rowIndex+1,_bookId:String(row[4]??'').trim()})}return out}}}throw new Error('Coleção: cabeçalho AUTORES / TITULO / TENHO não encontrado')}
function price(v){if(v==null||v==='')return null;let s=String(v).trim().replace(/[R$\s]/g,'').replace(/[^\d,.\-]/g,'');if(!s)return null;const c=s.lastIndexOf(','),d=s.lastIndexOf('.');if(c>=0&&d>=0)s=d>c?s.replace(/,/g,''):s.replace(/\./g,'').replace(',','.');else if(c>=0)s=(s.length-c-1===2)?s.replace(/\./g,'').replace(',','.'):s.replace(/,/g,'');else if(d>=0&&s.length-d-1!==2)s=s.replace(/\./g,'');const n=Number(s);return Number.isFinite(n)?n:null}
function dateISO(s){if(!s)return null;const m=String(s).match(/(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2})(?::(\d{2}))?h?)?/);const d=m?new Date(+m[3],+m[2]-1,+m[1],+(m[4]||0),+(m[5]||0)):new Date(s);return Number.isNaN(d.getTime())?null:d.toISOString()}
function rowLink(r){const raw=col(r,['Link','URL']);if(!raw)return'';const parts=raw.split('|').map(x=>x.trim()).filter(Boolean),urls=parts.filter(x=>/^https?:\/\//i.test(x)),ids=parts.filter(x=>/^\d+$/.test(x)),house=urls.find(u=>!norm(u).includes('leiloesbr com br')),id=ids.at(-1);if(house&&id){try{const u=new URL(house);return `${u.protocol}//${u.host}/peca.asp?ID=${encodeURIComponent(id)}`}catch{}}return urls.find(u=>/peca|lote/i.test(u))||house||urls[0]||''}
function own(v){const s=norm(v);if(s.includes('mesma edicao'))return'same';if(s.includes('outra edicao'))return'other';return'missing'}
function enrichMarket(r,i){const author=col(r,['Autor','Author']),title=col(r,['Título','Titulo','Obra','Title'])||col(r,['Descrição completa','Descricao completa','Comentários','Comentarios']).slice(0,120)||'Item sem título',year=Number((col(r,['Ano da edição','Ano da edicao','Ano','Year']).match(/\b(1[5-9]\d{2}|20\d{2})\b/)||[])[1])||null,typeRaw=norm(col(r,['Tipo','Tipo do item','Categoria'])),desc=col(r,['Descrição completa','Descricao completa','Comentários','Comentarios']),type=typeRaw.includes('document')?'documento':typeRaw.includes('livr')?'livro':/\b(carta|manuscrito|autografo|oficio)\b/.test(norm(desc))?'documento':'livro',edition=col(r,['Edição','Edicao']),publisher=col(r,['Editora']),status=norm(col(r,['Status'])),auctionDate=dateISO(col(r,['Data do pregão','Data do pregao','Pregão','Pregao','Data'])),detected=dateISO(col(r,['Detectado em','Detectado'])),initial=price(col(r,['Lance inicial (R$)','Lance inicial','Preço','Preco'])),final=price(col(r,['Valor final (R$)','Valor final','Preço final','Preco final'])),signed=norm(col(r,['Assinado?','Assinado']))==='sim',first=norm(col(r,['1ª edição?','1a edicao?','1a edicao']))==='sim'||/\b(1a edicao|primeira edicao|1 edicao)\b/.test(norm(desc+' '+edition)),ownership=own(col(r,['Situação na coleção','Situacao na colecao'])),image=col(r,['Imagem','URL da imagem','Image']),auctioneer=col(r,['Leiloeiro','Casa de leilão','Casa de leilao']),city=col(r,['Cidade']),link=rowLink(r),search=norm([author,title,year,publisher,edition,desc.slice(0,700),auctioneer,city].join(' ')),key=`m:${i}`;return{i,key,source:'leilao',author,title,year,type,desc,edition,publisher,status,auctionDate,detected,initial,final,signed,first,ownership,image,auctioneer,city,link,search}}
function enrichEstante(r,i){const author=col(r,['Autor'])||'Autor não identificado',title=col(r,['Título','Titulo'])||'Item sem título',year=extractYear(col(r,['Ano']))||extractYear(title),final=price(col(r,['Preço (R$)','Preco (R$)','Preço','Preco'])),link=col(r,['Link']),detected=dateISO(col(r,['Visto em','Visto'])),search=norm([author,title,year].join(' ')),key=`ev:${i}`;return{i,key,source:'estante',author,title,year,type:'livro',desc:'',edition:'',publisher:'',status:'',auctionDate:null,detected,initial:final,final,signed:false,first:false,ownership:'missing',image:'',auctioneer:'Estante Virtual',city:'',link,search}}
function enrichCollection(r,i){const author=col(r,['AUTORES','Autores','AUTOR','Autor'])||'Autor não identificado',title=col(r,['TITULO','TÍTULO','Título','Titulo'])||'Item sem título',year=extractYear(col(r,['ANO','Ano','Ano da edição','Ano da edicao']))||extractYear(title),status=String(col(r,['STATUS','Status'])).trim().toUpperCase(),owned=status==='TENHO'||(!status&&col(r,['TENHO','Tenho'])!==''),desire=!owned&&['sim','x','1','true'].includes(norm(col(r,['DESEJO','Desejo']))),value=price(col(r,['VALOR PAGO','Valor Pago','Valor pago','VALOR','Valor'])),acquired=dateISO(col(r,['DATA DE AQUISIÇÃO','DATA DE AQUISICAO','Data de Aquisição','Data de Aquisicao','DATA','Data'])),comment=col(r,['COMENTARIO','COMENTÁRIO','Comentario','Comentário']),description=col(r,['DESCRIÇÃO','DESCRICAO','Descrição','Descricao']),edition=col(r,['EDIÇÃO','EDICAO','Edição','Edicao']),publisher=col(r,['EDITORA','Editora']),dimensions=col(r,['DIMENSÕES','DIMENSOES','Dimensões','Dimensoes']),condition=col(r,['CONDIÇÃO','CONDICAO','Condição','Condicao','ESTADO DE CONSERVAÇÃO','ESTADO DE CONSERVACAO']),binding=col(r,['ENCADERNAÇÃO','ENCADERNACAO','Encadernação','Encadernacao']),pages=col(r,['PÁGINAS','PAGINAS','Páginas','Paginas']),provenance=col(r,['PROVENIÊNCIA','PROVENIENCIA','Proveniência','Proveniencia']),restoration=col(r,['RESTAURO','Restauro']),signature=col(r,['ASSINATURA','AUTÓGRAFO','AUTOGRAFO']),dedication=col(r,['DEDICATÓRIA','DEDICATORIA']),exLibris=col(r,['EX LIBRIS','EX-LIBRIS']),purchaseHouse=col(r,['LEILOEIRO','CASA','ORIGEM','VENDEDOR']),lotImage=col(r,['IMAGEM LOTE','Imagem lote']),lotLink=col(r,['LINK LOTE','LINK DO LOTE','URL LOTE']),lotAuctionDate=dateISO(col(r,['DATA LEILÃO','DATA LEILAO','DATA DO LEILAO','Data leilao'])),images=['IMAGEM CAPA','IMAGEM_CAPA','Imagem capa','FOTO','Foto','IMAGEM 1','Imagem 1','IMAGEM 2','Imagem 2','IMAGEM 3','Imagem 3','IMAGEM 4','Imagem 4','IMAGEM 5','Imagem 5'].map(k=>col(r,[k])).filter(Boolean),group=PATRONS.some(x=>norm(x)===norm(author))?'patrons':'founders',search=norm([author,title,year,publisher,edition,comment,description,status].join(' ')),key=`c:${i}`,bookId=Number(r._bookId||col(r,['REFERÊNCIA','REFERENCIA','REF','ID','NÚMERO','NUMERO','col_4']))||null,sheetRow=Number(r._sheetRow)||null;return{i,key,bookId,sheetRow,author,title,year,status,owned,desire,value,acquired,comment,description,edition,publisher,dimensions,condition,binding,pages,provenance,restoration,signature,dedication,exLibris,purchaseHouse,lotImage,lotLink,lotAuctionDate,images,group,search}}
function startOfToday(){const d=new Date();d.setHours(0,0,0,0);return d}
function validAuctionDate(r){if(!r.auctionDate)return null;const d=new Date(r.auctionDate);return Number.isNaN(d.getTime())?null:d}
function isCurrent(r){const d=validAuctionDate(r);return !d||d>=startOfToday()}
function isPastAuction(r){const d=validAuctionDate(r);return !!d&&d<startOfToday()}
async function fetchText(url){const r=await fetch(url,{headers:{'user-agent':'CLIO-Radar-Builder/1.0'}});if(!r.ok)throw new Error(`${url}: HTTP ${r.status}`);return r.text()}
async function writeJSON(name,data){await fs.writeFile(path.join(DATA,name),JSON.stringify(data));}
async function wikipediaPhoto(name){try{const api=`https://pt.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(name.replace(/ /g,'_'))}`;const r=await fetch(api,{headers:{'user-agent':'CLIO-Radar-Builder/1.0 (acervo pessoal)'}});if(!r.ok)return null;const j=await r.json();return j.originalimage?.source||j.thumbnail?.source||null}catch{return null}}
async function photoFor(name){const file=`${slug(name)}.webp`,dest=path.join(PHOTOS,file),n=norm(name),candidates=[];if(PHOTO_OVERRIDES[n])candidates.push(PHOTO_OVERRIDES[n]);candidates.push(`https://www.academia.org.br/sites/default/files/academicos/fotografias/${slug(name)}.jpg`);const wiki=await wikipediaPhoto(name);if(wiki)candidates.push(wiki);for(const url of [...new Set(candidates)]){try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 CLIO-Radar/1.0'}});if(!r.ok)continue;const type=r.headers.get('content-type')||'';if(!type.startsWith('image/'))continue;const buf=Buffer.from(await r.arrayBuffer());await sharp(buf).rotate().resize(320,320,{fit:'contain',background:{r:239,g:232,b:218,alpha:1},withoutEnlargement:true}).webp({quality:76}).toFile(dest);return{file:`assets/autores/${file}`,source:url,ok:true}}catch(e){console.warn(`Falha de foto ${name} em ${url}: ${e.message}`)}}console.warn(`Foto não encontrada: ${name}. Mantendo placeholder local.`);return{file:`assets/autores/${file}`,source:null,ok:false}}
await fs.mkdir(DATA,{recursive:true});await fs.mkdir(PHOTOS,{recursive:true});
const marketText=process.env.MARKET_FILE?await fs.readFile(process.env.MARKET_FILE,'utf8'):await fetchText(MARKET_URL);
const collectionText=process.env.SKIP_COLLECTION==='1'?null:(process.env.COLLECTION_FILE?await fs.readFile(process.env.COLLECTION_FILE,'utf8'):await fetchText(COLLECTION_URL));
async function readOptionalText(url,file){if(url)return fetchText(url);try{return await fs.readFile(path.join(ROOT,file),'utf8')}catch{return null}}
const estanteCurrentText=await readOptionalText(ESTANTE_CURRENT_URL,ESTANTE_CURRENT_FILE);
const estanteHistoryText=await readOptionalText(ESTANTE_HISTORY_URL,ESTANTE_HISTORY_FILE);
const estanteStatus=await(async()=>{try{return JSON.parse(await fs.readFile(path.join(ROOT,'raw','estante-status.json'),'utf8'))}catch{return null}})();
const market=parseCSV(marketText).map(enrichMarket),auctionCurrent=market.filter(isCurrent),history=market.filter(r=>isPastAuction(r)&&r.final!=null).sort((a,b)=>String(b.auctionDate||'').localeCompare(String(a.auctionDate||'')));
let nextEstanteId=market.length;
const estanteCurrent=estanteCurrentText?parseCSV(estanteCurrentText).map(r=>enrichEstante(r,nextEstanteId++)):[];
const estanteHistory=estanteHistoryText?parseCSV(estanteHistoryText).map(r=>enrichEstante(r,nextEstanteId++)):[];
const current=[...auctionCurrent,...estanteCurrent],searchIndex=[...market,...estanteCurrent,...estanteHistory];
const collection=collectionText?parseCollectionCSV(collectionText).map(enrichCollection):[];
await writeJSON('current.json',current);await writeJSON('history-index.json',history);await writeJSON('search-index.json',searchIndex);await writeJSON('estante-history.json',estanteHistory);if(collection.length)await writeJSON('collection.json',collection);
const authors=[];for(const name of [...PATRONS,...FOUNDERS]){const p=await photoFor(name);authors.push({name,group:PATRONS.includes(name)?'patrons':'founders',photo:p.file,photoReady:p.ok,source:p.source})}await writeJSON('authors.json',authors);
const generatedAt=new Date().toISOString(),version=crypto.createHash('sha256').update(marketText+'\n'+(collectionText||'')+'\n'+(estanteCurrentText||'')+'\n'+(estanteHistoryText||'')).digest('hex').slice(0,16);await writeJSON('manifest.json',{version,generatedAt,files:{current:'data/current.json',history:'data/history-index.json',search:'data/search-index.json',estanteHistory:'data/estante-history.json',collection:collection.length?'data/collection.json':null,authors:'data/authors.json'},counts:{current:current.length,history:history.length,market:market.length,estanteCurrent:estanteCurrent.length,estanteHistory:estanteHistory.length,collection:collection.length,authors:authors.length},estante:estanteStatus});
console.log(JSON.stringify({version,current:current.length,history:history.length,market:market.length,estanteCurrent:estanteCurrent.length,estanteHistory:estanteHistory.length,collection:collection.length,photos:authors.filter(a=>a.photoReady).length},null,2));
